import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import styles from '../../styles/History.module.css';

import { useRecoilState, useRecoilValue } from 'recoil';
import apiState from '../../state/apiState';
import apiStateB from '../../state/apiStateResponseHistory';
import apiSelector from '../../state/apiSelector';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import Header from '../Header';
import { getRandom } from '../../ts/util';

type Props = {
  pokemon: any;
};

// 各ポケモンごとの個別ページ。SSGビルド用サンプル
const ContentsId: NextPage<Props> = ({ pokemon }) => {
  // console.log('pokemon', pokemon);

  // 読込中
  const [isLoading, setIsLoading] = useState<boolean>(false);

  // データ
  const [pokemonState, setPokemonState] = useState<any>({ hoge: 'null' });

  // 発火イベント
  const onClickApiGet = async () => {
    console.log('onClickApiGet');

    // ローディング状態に
    setIsLoading(true);

    // Noを取得
    const num: number = getRandom(1, 151);

    // API通信（GET）
    const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${num}`, {
      method: 'GET', // *GET, POST, PUT, DELETE, etc.
      mode: 'cors', // no-cors, *cors, same-origin
      cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
      credentials: 'same-origin', // include, *same-origin, omit
      headers: {
        'Content-Type': 'application/json',
        // 'Content-Type': 'application/x-www-form-urlencoded',
      },
      redirect: 'follow', // manual, *follow, error
      referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
      // body: JSON.stringify(data), // 本文のデータ型は "Content-Type" ヘッダーと一致させる必要があります
    });
    // console.log('res', await res.json());
    const resJson: never = (await res.json()) as never;
    console.log('resJson', resJson);

    // APIレスポンスをuseStateで格納
    setPokemonState(resJson);

    // ローディング状態解除
    setIsLoading(false);
  };

  return (
    <>
      {/* ヘッダー */}
      <Header></Header>

      <div className={styles.container}>
        {/* メタデータ */}
        <Head>
          <title>個体 {pokemon.name}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>個体</h1>
          <br />
          <br />

          {/* 画像 */}
          <div>
            <img
              src={pokemon.sprites.front_default}
              width={320}
              height={320}
              alt="pika"
              // onError={(e) => {
              //   e.currentTarget.src = `https://placehold.jp/32/003060/e0e0e0/300x200.png?text=hoge`;
              // }}
              className={styles.image}
              data-load="done"
              // onLoad={onLoad}
              // ref={imgElement}
            />
          </div>

          <br />
          <br />

          {/* データ */}
          {/* <div>画像URL</div> */}
          <div>No：{pokemon.order}</div>
          <div>Name：「{pokemon.name}」</div>

          <br />
          <br />

          {/* イベントボタン */}
          <div>
            <button onClick={onClickApiGet}>新規API通信</button>
          </div>

          <br />
          <br />

          {/* fetchデータログ */}
          <div>新規fetchデータ</div>
          <div>{JSON.stringify(pokemonState)}</div>

          {/* <div>{JSON.stringify(pokemon)}</div> */}
          {/* <div>{pokemon.name}</div> */}
        </main>

        {/* フッター */}
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

//どんなpathがあるか
export const getStaticPaths = async () => {
  const paths = [`/contents/1`, `/contents/2`, `/contents/3`];
  return { paths, fallback: false };
};

//各ページのレンダリング
export const getStaticProps = async (context: any) => {
  // idを取得
  const id = context.params.id;

  // SSGする用のAPI GET
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`, {
    method: 'GET', // *GET, POST, PUT, DELETE, etc.
    mode: 'cors', // no-cors, *cors, same-origin
    cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
    credentials: 'same-origin', // include, *same-origin, omit
    headers: {
      'Content-Type': 'application/json',
      // 'Content-Type': 'application/x-www-form-urlencoded',
    },
    redirect: 'follow', // manual, *follow, error
    referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
    // body: JSON.stringify(data), // 本文のデータ型は "Content-Type" ヘッダーと一致させる必要があります
  });
  // console.log('res', await res.json());

  // 結果格納
  const json: never = (await res.json()) as never;
  // console.log('resJson', resJson);

  return {
    props: {
      pokemon: json,
    },
  };
};

export default ContentsId;
