import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import styles from '../../styles/History.module.css';

import { useRecoilState, useRecoilValue } from 'recoil';
import apiState from '../../state/apiState';
import apiStateB from '../../state/apiStateResponseHistory';
import apiSelector from '../../state/apiSelector';
import { useEffect } from 'react';
import Link from 'next/link';
import Header from '../Header';

// SSG用一覧ページ
const Contents: NextPage = () => {
  const pokemons = [
    {
      order: 1,
      name: '0001',
    },
    {
      order: 2,
      name: '0002',
    },
    {
      order: 3,
      name: '0003',
    },
  ];

  return (
    <>
      <Header></Header>
      <div className={styles.container}>
        <Head>
          <title>Contents</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>List</h1>
          <br />
          <br />

          {/* 一覧 */}
          <ul>
            {pokemons.map((pokemon: any) => (
              <li key={pokemon.order}>
                <Link href={`/contents/${pokemon.order}`}>
                  <a>{pokemon.name}</a>
                </Link>
              </li>
            ))}
          </ul>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default Contents;
