import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
// import styles from '../styles/Home.module.css';
import styles from '../../styles/History.module.css';

import { useRecoilState, useRecoilValue } from 'recoil';
import apiState from '../../state/apiState';
import apiStateB from '../../state/apiStateResponseHistory';
import apiSelector from '../../state/apiSelector';
import { useEffect } from 'react';
import Link from 'next/link';
import Header from '../header';

const History: NextPage = () => {
  // const [apiSample, setApiSample] = useRecoilState(apiState);

  // const apiHistory: any = useRecoilValue(apiSelector);
  // const [apiResponseHistory, setApiResponseHistory] = useRecoilState(apiStateB);
  const apiHistory: any[] = useRecoilValue(apiStateB);

  console.log('apiHistory', apiHistory);

  // useEffect(() => {
  //   const res = fetch('https://pokeapi.co/api/v2/pokemon/ditto');
  //   console.log('res', res);
  // }, []);

  return (
    <>
      <Header></Header>
      <div className={styles.container}>
        <Head>
          <title>API履歴</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>API履歴</h1>
          <br />
          <br />

          <div>
            {apiHistory &&
              apiHistory.map((data: any, i: number) => (
                <span key={i}>
                  <img
                    src={
                      data.sprites?.front_default ||
                      `https://placehold.jp/32/003060/e0e0e0/300x200.png?text=hoge`
                    }
                    width={160}
                    height={160}
                    alt="pika"
                    onError={(e) => {
                      e.currentTarget.src = `https://placehold.jp/32/003060/e0e0e0/300x200.png?text=hoge`;
                    }}
                  />
                </span>
              ))}
          </div>
          <br />
          <br />

          {/* <div>レスポンス生データ</div>
        <div>{apiHistory && <div>{JSON.stringify(apiHistory)}</div>}</div> */}

          {/* <div>
          <button onClick={onClickApiGet}>API GET</button>
        </div>

        <div>{JSON.stringify(apiSample)}</div> */}
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    </>
  );
};

export default History;
